# Writes browser/webp_tables.h: the constant tables of the VP8 (RFC 6386) and WebP
# lossless formats. They are specification constants; this script copies them out of a
# libwebp build (the one inside Pillow) so that no digit is mistyped, finding each table
# by the values it is known to start with.
import os
import PIL

blob = open(os.path.join(os.path.dirname(PIL.__file__), '_webp.cp311-win_amd64.pyd'), 'rb').read()


def find(seq):
    i = blob.find(bytes(seq))
    assert i >= 0, seq[:12]
    return i


def table(off, n):
    return list(blob[off:off + n])


proba0 = table(find([128] * 33 + [253, 136, 254, 255, 228, 219]), 4 * 8 * 3 * 11)
update = table(find([255] * 33 + [176, 246, 255]), 4 * 8 * 3 * 11)
bmodes = table(find([231, 120, 48, 89, 115, 113, 120, 152, 112]), 10 * 10 * 9)
dc = table(find([4, 5, 6, 7, 8, 9, 10, 10, 11, 12, 13, 14, 15, 16, 17, 17]), 128)
ac_off = find(b''.join(v.to_bytes(2, 'little') for v in range(4, 20)))
ac = [int.from_bytes(blob[ac_off + 2 * i:ac_off + 2 * i + 2], 'little') for i in range(128)]
plane = table(find([0x18, 0x07, 0x17, 0x19, 0x28, 0x06, 0x27, 0x29, 0x16, 0x1a]), 120)

# sanity: the last entries every copy of the specification agrees on
assert dc[-1] == 157 and ac[-1] == 284 and plane[-1] == 0x70
assert bmodes[-9:] == [112, 19, 12, 61, 195, 128, 48, 4, 24]


def c_array(name, ctype, dims, values):
    lines = []
    per = dims[-1]
    for i in range(0, len(values), per):
        lines.append('    ' + ', '.join(str(v) for v in values[i:i + per]) + ',')
    shape = ''.join(f'[{d}]' for d in dims)
    flat = f'static const {ctype} {name}{shape} = {{\n' if len(dims) == 1 else None
    if len(dims) == 1:
        return f'static const {ctype} {name}[{dims[0]}] = {{\n' + '\n'.join(lines) + '\n};\n'
    # multi-dimensional arrays are emitted flat and indexed by hand
    total = 1
    for d in dims:
        total *= d
    return (f'// {name}{shape}, flattened\n'
            f'static const {ctype} {name}[{total}] = {{\n' + '\n'.join(lines) + '\n};\n')


out = ['// webp_tables.h — constant tables of the VP8 (RFC 6386) and WebP lossless formats.',
       '// Generated by tests/gen_webp_tables.py; do not edit.',
       '#pragma once',
       '#include <cstdint>',
       '',
       'namespace webp_tables {',
       '',
       c_array('kCoeffsProba0', 'uint8_t', [4, 8, 3, 11], proba0),
       c_array('kCoeffsUpdateProba', 'uint8_t', [4, 8, 3, 11], update),
       c_array('kBModesProba', 'uint8_t', [10, 10, 9], bmodes),
       c_array('kDcTable', 'uint8_t', [16], dc).replace('[16]', '[128]'),
       c_array('kAcTable', 'uint16_t', [16], ac).replace('[16]', '[128]'),
       c_array('kCodeToPlane', 'uint8_t', [10], plane).replace('[10]', '[120]'),
       '}  // namespace webp_tables',
       '']
open(os.path.join(os.path.dirname(__file__), '..', 'browser', 'webp_tables.h'), 'w', encoding='utf-8').write('\n'.join(out))
print('wrote browser/webp_tables.h')
