# Writes browser/hpack_huffman.h: the Huffman code of HPACK (RFC 7541, Appendix B), read
# from the RFC text so that no code is typed in by hand.
#   python tests/gen_hpack_huffman.py [rfc7541.txt]   (downloads the RFC if no file is given)
import re, sys, urllib.request

if len(sys.argv) > 1:
    text = open(sys.argv[1], encoding='utf-8').read()
else:
    text = urllib.request.urlopen('https://www.rfc-editor.org/rfc/rfc7541.txt').read().decode()

start = text.index('Appendix B.  Huffman Code')
rows = re.findall(r'\(\s*(\d+)\)\s+\|([01|]+)\s+([0-9a-f]+)\s+\[\s*(\d+)\]', text[start:])
codes = {}
for sym, bits, hexcode, length in rows:
    sym, length, code = int(sym), int(length), int(hexcode, 16)
    assert bits.replace('|', '') == format(code, f'0{length}b'), sym  # the two columns agree
    codes[sym] = (code, length)
assert sorted(codes) == list(range(257)), 'expected 256 octets + EOS'

with open('browser/hpack_huffman.h', 'w', encoding='utf-8', newline='\n') as f:
    f.write('// hpack_huffman.h — generated by tests/gen_hpack_huffman.py from RFC 7541 Appendix B.\n')
    f.write('// kHuffman[sym] = {code (aligned to the least significant bit), length in bits}; 256 = EOS.\n')
    f.write('#pragma once\n#include <cstdint>\n\n')
    f.write('struct HuffmanCode { uint32_t code; uint8_t bits; };\n')
    f.write('static const HuffmanCode kHuffman[257] = {\n')
    for s in range(257):
        c, n = codes[s]
        f.write(f'    {{0x{c:x}, {n}}},' + ('\n' if s % 4 == 3 or s == 256 else ' '))
    f.write('};\n')
print('wrote browser/hpack_huffman.h (257 codes)')
